spring:
  profiles:
    default: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    open-in-view: false
    show-sql: true
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  web:
    resources:
      cache:
        period: 0
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
#logging:
#  level:
#    org.hibernate.SQL: INFO
