spring:
  profiles:
    default: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    open-in-view: false
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  web:
    resources:
      cache:
        period: 0
logging:
  level:
    org.hibernate.SQL: INFO